[target.x86_64-pc-windows-msvc]
linker = "rust-lld.exe"
rustflags = ["-Zlocation-detail=none"]
[target.x86_64-apple-darwin]
rustflags = ["-Zlocation-detail=none"]
[target.aarch64-apple-darwin]
rustflags = ["-Zlocation-detail=none"]
[target.x86_64-linux-unknown]
rustflags = ["-Zlocation-detail=none"]
