[target.x86_64-pc-windows-msvc]
rustflags = []
[target.x86_64-apple-darwin]
rustflags = []
[target.aarch64-apple-darwin]
rustflags = []
[target.x86_64-unknown-linux-gnu]
rustflags = []
[target.x86_64-unknown-linux-musl]
rustflags = ["-Ctarget-feature=-crt-static", "-Clink-self-contained=on"]
