name: Pull Request
run-name: Pull Request for ${{ github.ref_name }} by ${{ github.actor }}

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions: write-all

on:
  pull_request: {}
  workflow_dispatch: {}
  push:
    branches:
      - trunk-merge/**

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest-8-cores

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build -q
    - name: Run tests
      run: cargo test --verbose
    - name: Install JUnit transformer
      run: cargo install cargo-junit
    - name: Generate JUnit report
      run: cargo junit --output ${{ github.workspace }}/target/junit.xml
    - name: Upload results
      if: "!cancelled()"
      uses: trunk-io/analytics-uploader@main
      with:
        junit-paths: ${{ github.workspace }}/target/**/*junit.xml
        org-slug: trunk-io
        token: ${{ secrets.TRUNK_API_TOKEN }}
      continue-on-error: true
